### ISSUE TITLE
Pure bf16 training numerical stability

### ISSUE THREAD

**Issue by isayoften** [LambdaLabsML/distributed-training-guide#47]
Why don't you use mixed precision and train in pure bf16? What about the convergence of the model and the numerical stability of sensitive operations?

**Comment by corey-lambda** [comment]
Mainly for simplicity of code - this repo is mainly focused on distributed training practices. Don't want to add too many features to the code (especially since it all builds on each other). The intention behind the code is to show how to use distributed APIs, not to be the "best practices" for all training in general.

Other things that would likely not be added to this repo (again because they are orthogonal to training distributed):
- Model EMA
- Other types of models (diffusion/image/etc)
- dataset augmentation
- configurable lr scheduler
- regularization
- evaluation (though I could see adding a chapter on how to do this in a distributed manner)

There's likely a lot more that I'm just not thinking of off the top of my head.

Additionally, just some further reading for folks who are interested, there has been some research on pure bf16 training that you might find intereseting:

[Standalone 16-bit Training: Missing Study for Hardware-Limited Deep Learning Practitioners
](https://arxiv.org/abs/2305.10947)
